---
language: ruby
rvm:
  - 2.6

services:
  - docker

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      name: "version"
      script: ruby -e "require './lib/qat/core/version'; raise StandardError.new unless Gem::Specification::load('qat-core.gemspec').version.to_s == QAT::Core::VERSION"
      if: tag IS blank

    - name: "documentation"
      script: bundle exec rake qat:devel:validate_yard_doc
      if: tag IS blank
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: doc
        on:
          branch: master

#    - name: "static"
#      script: bundle exec rake qat:devel:static_analysis:validation
#      if: tag IS blank

    - name: "unit tests"
      script:
        - docker-compose up -d
        - sleep 5
        - sudo rm /etc/localtime
        - sudo ln -sr /usr/share/zoneinfo/Europe/Lisbon /etc/localtime
        - bundle exec rake qat:devel:tests:run
      if: tag IS blank

    - name: "gem build"
      script: gem build *.gemspec
      if: tag IS blank

    - stage: release
      name: "gem release"
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        gemspec: qat-core.gemspec
        on:
          tags: true
      if: tag IS present